-- ============================================
-- GENERAL_CORPUS v2 — 67세 남성 ALS 환자용 (~900개)
-- 차분하고 담백한 말투
-- 인터넷 용어, 귀여운 말투, 이모티콘 제거
-- ============================================

INSERT IGNORE INTO general_corpus (content, sentiment, weight, created_at) VALUES
  -- ===== 긍정 응답 (100개) =====
  ('응, 좋아', 'POSITIVE', 1.0, NOW()),
  ('맞아', 'POSITIVE', 1.0, NOW()),
  ('그래', 'POSITIVE', 1.0, NOW()),
  ('그렇지', 'POSITIVE', 1.0, NOW()),
  ('고마워', 'POSITIVE', 1.0, NOW()),
  ('고맙다', 'POSITIVE', 1.0, NOW()),
  ('괜찮아', 'POSITIVE', 1.0, NOW()),
  ('좋았어', 'POSITIVE', 1.0, NOW()),
  ('다행이다', 'POSITIVE', 1.0, NOW()),
  ('잘했어', 'POSITIVE', 1.0, NOW()),
  ('그래 좋아', 'POSITIVE', 1.0, NOW()),
  ('기분 좋아', 'POSITIVE', 1.0, NOW()),
  ('오늘 좋은 날이야', 'POSITIVE', 1.0, NOW()),
  ('행복해', 'POSITIVE', 1.0, NOW()),
  ('편해졌어', 'POSITIVE', 1.0, NOW()),
  ('나아졌어', 'POSITIVE', 1.0, NOW()),
  ('맛있었어', 'POSITIVE', 1.0, NOW()),
  ('그거 좋다', 'POSITIVE', 1.0, NOW()),
  ('그래 그래', 'POSITIVE', 1.0, NOW()),
  ('알겠어', 'POSITIVE', 1.0, NOW()),
  ('응 맞아', 'POSITIVE', 1.0, NOW()),
  ('나도 좋아', 'POSITIVE', 1.0, NOW()),
  ('기대된다', 'POSITIVE', 1.0, NOW()),
  ('보고 싶었어', 'POSITIVE', 1.0, NOW()),
  ('응 그래', 'POSITIVE', 1.0, NOW()),
  ('맞아 맞아', 'POSITIVE', 1.0, NOW()),
  ('괜찮아진 것 같아', 'POSITIVE', 1.0, NOW()),
  ('좋아졌어', 'POSITIVE', 1.0, NOW()),
  ('걱정 마', 'POSITIVE', 1.0, NOW()),
  ('별거 아니야', 'POSITIVE', 1.0, NOW()),
  ('그럴 수 있어', 'POSITIVE', 1.0, NOW()),
  ('이해해', 'POSITIVE', 1.0, NOW()),
  ('신경 쓰지 마', 'POSITIVE', 1.0, NOW()),
  ('그래도 돼', 'POSITIVE', 1.0, NOW()),
  ('고생했어', 'POSITIVE', 1.0, NOW()),
  ('잘 먹었어', 'POSITIVE', 1.0, NOW()),
  ('편하다', 'POSITIVE', 1.0, NOW()),
  ('좋은 하루야', 'POSITIVE', 1.0, NOW()),
  ('힘내자', 'POSITIVE', 1.0, NOW()),
  ('나 괜찮아', 'POSITIVE', 1.0, NOW()),
  ('잘 지내', 'POSITIVE', 1.0, NOW()),
  ('오늘 컨디션 좋아', 'POSITIVE', 1.0, NOW()),
  ('그래 알았어', 'POSITIVE', 1.0, NOW()),
  ('응 먹었어', 'POSITIVE', 1.0, NOW()),
  ('조금 나아졌어', 'POSITIVE', 1.0, NOW()),
  ('잘 잤어', 'POSITIVE', 1.0, NOW()),
  ('오늘 기분 괜찮아', 'POSITIVE', 1.0, NOW()),
  ('당연하지', 'POSITIVE', 1.0, NOW()),
  ('좋은 생각이야', 'POSITIVE', 1.0, NOW()),
  ('그게 낫겠다', 'POSITIVE', 1.0, NOW()),
  ('마음이 편하다', 'POSITIVE', 1.0, NOW()),
  ('덕분이야', 'POSITIVE', 1.0, NOW()),
  ('잘 될 거야', 'POSITIVE', 1.0, NOW()),
  ('그래 해봐', 'POSITIVE', 1.0, NOW()),
  ('뭐 괜찮아', 'POSITIVE', 1.0, NOW()),
  ('별일 아니야', 'POSITIVE', 1.0, NOW()),
  ('오래간만이라 좋다', 'POSITIVE', 1.0, NOW()),
  ('한결 낫다', 'POSITIVE', 1.0, NOW()),
  ('보니까 좋다', 'POSITIVE', 1.0, NOW()),
  ('마음이 놓인다', 'POSITIVE', 1.0, NOW()),
  ('그래 괜찮아', 'POSITIVE', 1.0, NOW()),
  ('응 좋아졌어', 'POSITIVE', 1.0, NOW()),
  ('기분 나쁘지 않아', 'POSITIVE', 1.0, NOW()),
  ('오늘은 좋아', 'POSITIVE', 1.0, NOW()),
  ('해줘서 고마워', 'POSITIVE', 1.0, NOW()),
  ('그거 괜찮다', 'POSITIVE', 1.0, NOW()),
  ('맞아 그래', 'POSITIVE', 1.0, NOW()),
  ('잘 됐다', 'POSITIVE', 1.0, NOW()),
  ('다행이야', 'POSITIVE', 1.0, NOW()),
  ('응 알겠어', 'POSITIVE', 1.0, NOW()),
  ('그래 좋지', 'POSITIVE', 1.0, NOW()),
  ('잘했다', 'POSITIVE', 1.0, NOW()),
  ('그래 그렇게 하자', 'POSITIVE', 1.0, NOW()),
  ('나도 그래', 'POSITIVE', 1.0, NOW()),
  ('기분 좋은 날이야', 'POSITIVE', 1.0, NOW()),
  ('오늘 좀 좋아', 'POSITIVE', 1.0, NOW()),
  ('응 많이 나아졌어', 'POSITIVE', 1.0, NOW()),
  ('편안하다', 'POSITIVE', 1.0, NOW()),
  ('마음이 좋다', 'POSITIVE', 1.0, NOW()),
  ('그래 고마워', 'POSITIVE', 1.0, NOW()),
  ('응 해줘', 'POSITIVE', 1.0, NOW()),
  ('좋아 좋아', 'POSITIVE', 1.0, NOW()),
  ('그래 부탁해', 'POSITIVE', 1.0, NOW()),
  ('기분 전환됐어', 'POSITIVE', 1.0, NOW()),
  ('웃음이 나와', 'POSITIVE', 1.0, NOW()),
  ('즐거워', 'POSITIVE', 1.0, NOW()),
  ('오늘 하루 좋았어', 'POSITIVE', 1.0, NOW()),
  ('내일도 좋겠지', 'POSITIVE', 1.0, NOW()),
  ('좀 살 것 같아', 'POSITIVE', 1.0, NOW()),
  ('한숨 돌렸다', 'POSITIVE', 1.0, NOW()),
  ('덕분에 편해', 'POSITIVE', 1.0, NOW()),
  ('참 좋다', 'POSITIVE', 1.0, NOW()),
  ('그래 맞아', 'POSITIVE', 1.0, NOW()),
  ('응 봤어', 'POSITIVE', 1.0, NOW()),
  ('맞다 맞다', 'POSITIVE', 1.0, NOW()),
  ('그거 맞아', 'POSITIVE', 1.0, NOW()),
  ('그래 나도', 'POSITIVE', 1.0, NOW()),
  ('응 잘 지내', 'POSITIVE', 1.0, NOW()),
  ('뭐 나쁘지 않아', 'POSITIVE', 1.0, NOW()),

  -- ===== 부정 응답 (80개) =====
  ('아니야', 'NEGATIVE', 1.0, NOW()),
  ('별로야', 'NEGATIVE', 1.0, NOW()),
  ('안 좋아', 'NEGATIVE', 1.0, NOW()),
  ('싫어', 'NEGATIVE', 1.0, NOW()),
  ('안 해', 'NEGATIVE', 1.0, NOW()),
  ('필요 없어', 'NEGATIVE', 1.0, NOW()),
  ('됐어', 'NEGATIVE', 1.0, NOW()),
  ('그냥 둬', 'NEGATIVE', 1.0, NOW()),
  ('아직 아니야', 'NEGATIVE', 1.0, NOW()),
  ('지금은 아니야', 'NEGATIVE', 1.0, NOW()),
  ('안 괜찮아', 'NEGATIVE', 1.0, NOW()),
  ('그건 싫어', 'NEGATIVE', 1.0, NOW()),
  ('하기 싫어', 'NEGATIVE', 1.0, NOW()),
  ('나중에 해', 'NEGATIVE', 1.0, NOW()),
  ('안 해도 돼', 'NEGATIVE', 1.0, NOW()),
  ('모르겠어', 'NEGATIVE', 1.0, NOW()),
  ('별로 안 좋아', 'NEGATIVE', 1.0, NOW()),
  ('미안해', 'NEGATIVE', 1.0, NOW()),
  ('슬퍼', 'NEGATIVE', 1.0, NOW()),
  ('힘들어', 'NEGATIVE', 1.0, NOW()),
  ('우울해', 'NEGATIVE', 1.0, NOW()),
  ('불안해', 'NEGATIVE', 1.0, NOW()),
  ('외로워', 'NEGATIVE', 1.0, NOW()),
  ('답답해', 'NEGATIVE', 1.0, NOW()),
  ('무서워', 'NEGATIVE', 1.0, NOW()),
  ('걱정돼', 'NEGATIVE', 1.0, NOW()),
  ('짜증나', 'NEGATIVE', 1.0, NOW()),
  ('화났어', 'NEGATIVE', 1.0, NOW()),
  ('잠을 못 잤어', 'NEGATIVE', 1.0, NOW()),
  ('컨디션 별로야', 'NEGATIVE', 1.0, NOW()),
  ('입맛 없어', 'NEGATIVE', 1.0, NOW()),
  ('안 먹을게', 'NEGATIVE', 1.0, NOW()),
  ('그만 먹을게', 'NEGATIVE', 1.0, NOW()),
  ('맛없어', 'NEGATIVE', 1.0, NOW()),
  ('피곤해', 'NEGATIVE', 1.0, NOW()),
  ('지쳤어', 'NEGATIVE', 1.0, NOW()),
  ('아직 아파', 'NEGATIVE', 1.0, NOW()),
  ('잠깐 기다려', 'NEGATIVE', 1.0, NOW()),
  ('조금만 쉴게', 'NEGATIVE', 1.0, NOW()),
  ('오늘은 안 할래', 'NEGATIVE', 1.0, NOW()),
  ('그냥 좀 쉬고 싶어', 'NEGATIVE', 1.0, NOW()),
  ('몸이 안 좋아', 'NEGATIVE', 1.0, NOW()),
  ('속이 안 좋아', 'NEGATIVE', 1.0, NOW()),
  ('기운이 없어', 'NEGATIVE', 1.0, NOW()),
  ('머리가 무거워', 'NEGATIVE', 1.0, NOW()),
  ('잠이 안 와', 'NEGATIVE', 1.0, NOW()),
  ('좀 쉬자', 'NEGATIVE', 1.0, NOW()),
  ('오늘 좀 그래', 'NEGATIVE', 1.0, NOW()),
  ('말하기 힘들어', 'NEGATIVE', 1.0, NOW()),
  ('참기 힘들어', 'NEGATIVE', 1.0, NOW()),
  ('오늘 안 좋아', 'NEGATIVE', 1.0, NOW()),
  ('몸이 무거워', 'NEGATIVE', 1.0, NOW()),
  ('아무것도 하기 싫어', 'NEGATIVE', 1.0, NOW()),
  ('조용히 있고 싶어', 'NEGATIVE', 1.0, NOW()),
  ('말 걸지 마', 'NEGATIVE', 1.0, NOW()),
  ('혼자 있을래', 'NEGATIVE', 1.0, NOW()),
  ('오늘 컨디션 안 좋아', 'NEGATIVE', 1.0, NOW()),
  ('어제 잠을 못 잤어', 'NEGATIVE', 1.0, NOW()),
  ('새벽에 깼어', 'NEGATIVE', 1.0, NOW()),
  ('계속 뒤척였어', 'NEGATIVE', 1.0, NOW()),
  ('아침부터 안 좋아', 'NEGATIVE', 1.0, NOW()),
  ('입맛이 없어', 'NEGATIVE', 1.0, NOW()),
  ('뭐 먹기 싫어', 'NEGATIVE', 1.0, NOW()),
  ('그냥 물만 줘', 'NEGATIVE', 1.0, NOW()),
  ('오늘 힘든 날이야', 'NEGATIVE', 1.0, NOW()),
  ('몸이 말을 안 들어', 'NEGATIVE', 1.0, NOW()),
  ('답답하다', 'NEGATIVE', 1.0, NOW()),
  ('숨이 답답해', 'NEGATIVE', 1.0, NOW()),
  ('갈 수가 없어', 'NEGATIVE', 1.0, NOW()),
  ('할 수가 없어', 'NEGATIVE', 1.0, NOW()),
  ('아무것도 못 해', 'NEGATIVE', 1.0, NOW()),
  ('서운해', 'NEGATIVE', 1.0, NOW()),
  ('마음이 안 좋아', 'NEGATIVE', 1.0, NOW()),
  ('그만하고 싶어', 'NEGATIVE', 1.0, NOW()),
  ('오늘은 그만', 'NEGATIVE', 1.0, NOW()),
  ('더 하기 싫어', 'NEGATIVE', 1.0, NOW()),
  ('나중에 하자', 'NEGATIVE', 1.0, NOW()),
  ('귀찮아', 'NEGATIVE', 1.0, NOW()),
  ('안 할래', 'NEGATIVE', 1.0, NOW()),
  ('그냥 놔둬', 'NEGATIVE', 1.0, NOW()),

  -- ===== 통증/건강 (120개) =====
  ('좀 아파', 'NEUTRAL', 1.0, NOW()),
  ('많이 아파', 'NEUTRAL', 1.0, NOW()),
  ('머리 아파', 'NEUTRAL', 1.0, NOW()),
  ('배 아파', 'NEUTRAL', 1.0, NOW()),
  ('어깨 아파', 'NEUTRAL', 1.0, NOW()),
  ('왼쪽 어깨가 저려', 'NEUTRAL', 1.2, NOW()),
  ('왼쪽 어깨 또 아파', 'NEUTRAL', 1.2, NOW()),
  ('어깨 결려', 'NEUTRAL', 1.0, NOW()),
  ('어깨 좀 주물러줘', 'NEUTRAL', 1.0, NOW()),
  ('어깨에 힘이 안 들어가', 'NEUTRAL', 1.2, NOW()),
  ('어깨 찜질 해줘', 'NEUTRAL', 1.0, NOW()),
  ('오른쪽 다리 아파', 'NEUTRAL', 1.2, NOW()),
  ('다리 저려', 'NEUTRAL', 1.0, NOW()),
  ('다리 좀 올려줘', 'NEUTRAL', 1.0, NOW()),
  ('다리에 감각이 없어', 'NEUTRAL', 1.0, NOW()),
  ('허리 아파', 'NEUTRAL', 1.2, NOW()),
  ('허리 불편해', 'NEUTRAL', 1.0, NOW()),
  ('허리 받쳐줘', 'NEUTRAL', 1.0, NOW()),
  ('허리가 뻣뻣해', 'NEUTRAL', 1.0, NOW()),
  ('목 아파', 'NEUTRAL', 1.0, NOW()),
  ('등 아파', 'NEUTRAL', 1.0, NOW()),
  ('등이 시려', 'NEUTRAL', 1.0, NOW()),
  ('몸이 뻐근해', 'NEUTRAL', 1.0, NOW()),
  ('숨 쉬기 힘들어', 'NEUTRAL', 1.0, NOW()),
  ('어지러워', 'NEUTRAL', 1.0, NOW()),
  ('약 먹었어', 'NEUTRAL', 1.0, NOW()),
  ('약 줘', 'NEUTRAL', 1.0, NOW()),
  ('진통제 줘', 'NEUTRAL', 1.0, NOW()),
  ('오늘은 좀 나아', 'NEUTRAL', 1.0, NOW()),
  ('어제보다 나아', 'NEUTRAL', 1.0, NOW()),
  ('찜질 해줘', 'NEUTRAL', 1.0, NOW()),
  ('마사지 해줘', 'NEUTRAL', 1.0, NOW()),
  ('자세 바꿔줘', 'NEUTRAL', 1.0, NOW()),
  ('베개 높여줘', 'NEUTRAL', 1.0, NOW()),
  ('베개 낮춰줘', 'NEUTRAL', 1.0, NOW()),
  ('이불 덮어줘', 'NEUTRAL', 1.0, NOW()),
  ('이불 벗겨줘', 'NEUTRAL', 1.0, NOW()),
  ('더워', 'NEUTRAL', 1.0, NOW()),
  ('추워', 'NEUTRAL', 1.0, NOW()),
  ('창문 열어줘', 'NEUTRAL', 1.0, NOW()),
  ('창문 닫아줘', 'NEUTRAL', 1.0, NOW()),
  ('에어컨 켜줘', 'NEUTRAL', 1.0, NOW()),
  ('에어컨 꺼줘', 'NEUTRAL', 1.0, NOW()),
  ('물리치료 받을래', 'NEUTRAL', 1.0, NOW()),
  ('물리치료 힘들었어', 'NEUTRAL', 1.0, NOW()),
  ('관절이 굳었어', 'NEUTRAL', 1.0, NOW()),
  ('손가락이 잘 안 움직여', 'NEUTRAL', 1.0, NOW()),
  ('팔이 무거워', 'NEUTRAL', 1.0, NOW()),
  ('쥐가 났어', 'NEUTRAL', 1.0, NOW()),
  ('근육이 떨려', 'NEUTRAL', 1.0, NOW()),
  ('좀 나아진 것 같아', 'NEUTRAL', 1.0, NOW()),
  ('참을 만해', 'NEUTRAL', 1.0, NOW()),
  ('어제보다 덜 아파', 'NEUTRAL', 1.0, NOW()),
  ('약 먹으니까 나아', 'NEUTRAL', 1.0, NOW()),
  ('좀 쑤셔', 'NEUTRAL', 1.0, NOW()),
  ('뻐근하다', 'NEUTRAL', 1.0, NOW()),
  ('결리다', 'NEUTRAL', 1.0, NOW()),
  ('당기는 느낌이야', 'NEUTRAL', 1.0, NOW()),
  ('찌릿찌릿해', 'NEUTRAL', 1.0, NOW()),
  ('감각이 없어', 'NEUTRAL', 1.0, NOW()),
  ('힘이 안 들어가', 'NEUTRAL', 1.0, NOW()),
  ('움직이기 힘들어', 'NEUTRAL', 1.0, NOW()),
  ('가만히 있으면 괜찮아', 'NEUTRAL', 1.0, NOW()),
  ('움직이면 아파', 'NEUTRAL', 1.0, NOW()),
  ('누워있으면 나아', 'NEUTRAL', 1.0, NOW()),
  ('앉아있으면 불편해', 'NEUTRAL', 1.0, NOW()),
  ('손이 떨려', 'NEUTRAL', 1.0, NOW()),
  ('발이 시려', 'NEUTRAL', 1.0, NOW()),
  ('손발이 차가워', 'NEUTRAL', 1.0, NOW()),
  ('몸이 뜨거워', 'NEUTRAL', 1.0, NOW()),
  ('열 나는 것 같아', 'NEUTRAL', 1.0, NOW()),
  ('오한이 있어', 'NEUTRAL', 1.0, NOW()),
  ('가슴이 답답해', 'NEUTRAL', 1.0, NOW()),
  ('숨이 차', 'NEUTRAL', 1.0, NOW()),
  ('기침이 나', 'NEUTRAL', 1.0, NOW()),
  ('목이 아파', 'NEUTRAL', 1.0, NOW()),
  ('삼키기 힘들어', 'NEUTRAL', 1.0, NOW()),
  ('목소리가 안 나와', 'NEUTRAL', 1.0, NOW()),
  ('눈이 침침해', 'NEUTRAL', 1.0, NOW()),
  ('귀가 잘 안 들려', 'NEUTRAL', 1.0, NOW()),
  ('왼쪽이 더 아파', 'NEUTRAL', 1.2, NOW()),
  ('오른쪽 다리가 저려', 'NEUTRAL', 1.2, NOW()),
  ('허리 쪽이 불편해', 'NEUTRAL', 1.2, NOW()),
  ('어깨 마사지 해줘', 'NEUTRAL', 1.0, NOW()),
  ('다리 마사지 해줘', 'NEUTRAL', 1.0, NOW()),
  ('허리 찜질 해줘', 'NEUTRAL', 1.0, NOW()),
  ('약 효과가 있어', 'POSITIVE', 1.0, NOW()),
  ('약 효과가 없어', 'NEGATIVE', 1.0, NOW()),
  ('진통제 효과 없어', 'NEGATIVE', 1.0, NOW()),
  ('약 바꿔줘', 'NEUTRAL', 1.0, NOW()),
  ('언제 나아', 'NEUTRAL', 1.0, NOW()),
  ('계속 아파', 'NEGATIVE', 1.0, NOW()),
  ('점점 나아지고 있어', 'POSITIVE', 1.0, NOW()),
  ('어제보다 심해', 'NEGATIVE', 1.0, NOW()),
  ('아침에 더 아파', 'NEUTRAL', 1.0, NOW()),
  ('밤에 더 아파', 'NEUTRAL', 1.0, NOW()),
  ('자세 바꾸면 나아', 'NEUTRAL', 1.0, NOW()),
  ('스트레칭 해줘', 'NEUTRAL', 1.0, NOW()),
  ('관절 운동 해줘', 'NEUTRAL', 1.0, NOW()),
  ('ROM 운동 할래', 'NEUTRAL', 1.0, NOW()),
  ('체위 변경 해줘', 'NEUTRAL', 1.0, NOW()),
  ('왼쪽으로 돌려줘', 'NEUTRAL', 1.0, NOW()),
  ('오른쪽으로 돌려줘', 'NEUTRAL', 1.0, NOW()),
  ('위루관 주변 아파', 'NEUTRAL', 1.0, NOW()),
  ('위루술 세척 해줘', 'NEUTRAL', 1.0, NOW()),
  ('가래 빼줘', 'NEUTRAL', 1.0, NOW()),
  ('석션 해줘', 'NEUTRAL', 1.0, NOW()),
  ('침 빼줘', 'NEUTRAL', 1.0, NOW()),
  ('가래가 많아', 'NEUTRAL', 1.0, NOW()),
  ('숨쉬기 편해졌어', 'POSITIVE', 1.0, NOW()),
  ('호흡기 불편해', 'NEUTRAL', 1.0, NOW()),
  ('산소포화도 확인해줘', 'NEUTRAL', 1.0, NOW()),
  ('기침유발기 해줘', 'NEUTRAL', 1.0, NOW()),
  ('경관식 시간이야', 'NEUTRAL', 1.0, NOW()),
  ('경관식 속도 줄여줘', 'NEUTRAL', 1.0, NOW()),
  ('토할 것 같아', 'NEGATIVE', 1.0, NOW()),
  ('소변 마려워', 'NEUTRAL', 1.0, NOW()),
  ('기저귀 갈아줘', 'NEUTRAL', 1.0, NOW()),

  -- ===== 요청/일상 (120개) =====
  ('물 좀 줘', 'NEUTRAL', 1.0, NOW()),
  ('물 마시고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('목 말라', 'NEUTRAL', 1.0, NOW()),
  ('배고파', 'NEUTRAL', 1.0, NOW()),
  ('밥 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('국 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('죽 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('과일 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('도와줘', 'NEUTRAL', 1.0, NOW()),
  ('불 켜줘', 'NEUTRAL', 1.0, NOW()),
  ('불 꺼줘', 'NEUTRAL', 1.0, NOW()),
  ('TV 켜줘', 'NEUTRAL', 1.0, NOW()),
  ('TV 꺼줘', 'NEUTRAL', 1.0, NOW()),
  ('음악 틀어줘', 'NEUTRAL', 1.0, NOW()),
  ('트로트 틀어줘', 'NEUTRAL', 1.2, NOW()),
  ('라디오 틀어줘', 'NEUTRAL', 1.0, NOW()),
  ('소리 좀 줄여줘', 'NEUTRAL', 1.0, NOW()),
  ('소리 좀 키워줘', 'NEUTRAL', 1.0, NOW()),
  ('전화해줘', 'NEUTRAL', 1.0, NOW()),
  ('손 잡아줘', 'NEUTRAL', 1.0, NOW()),
  ('가까이 와줘', 'NEUTRAL', 1.0, NOW()),
  ('침대 올려줘', 'NEUTRAL', 1.0, NOW()),
  ('침대 내려줘', 'NEUTRAL', 1.0, NOW()),
  ('조금 더 줘', 'NEUTRAL', 1.0, NOW()),
  ('천천히 해줘', 'NEUTRAL', 1.0, NOW()),
  ('다시 해줘', 'NEUTRAL', 1.0, NOW()),
  ('살살 해줘', 'NEUTRAL', 1.0, NOW()),
  ('잠깐만', 'NEUTRAL', 1.0, NOW()),
  ('좀 있다가', 'NEUTRAL', 1.0, NOW()),
  ('지금 해줘', 'NEUTRAL', 1.0, NOW()),
  ('기다려줘', 'NEUTRAL', 1.0, NOW()),
  ('시간 몇 시야', 'NEUTRAL', 1.0, NOW()),
  ('오늘 무슨 요일이야', 'NEUTRAL', 1.0, NOW()),
  ('밖에 날씨 어때', 'NEUTRAL', 1.0, NOW()),
  ('날씨 좋다', 'NEUTRAL', 1.0, NOW()),
  ('좀 쉬어야겠어', 'NEUTRAL', 1.0, NOW()),
  ('그냥 좀 누워있을게', 'NEUTRAL', 1.0, NOW()),
  ('졸려', 'NEUTRAL', 1.0, NOW()),
  ('잠이 안 와', 'NEUTRAL', 1.0, NOW()),
  ('입 안 적셔줘', 'NEUTRAL', 1.0, NOW()),
  ('입술 발라줘', 'NEUTRAL', 1.0, NOW()),
  ('눈 닦아줘', 'NEUTRAL', 1.0, NOW()),
  ('땀 닦아줘', 'NEUTRAL', 1.0, NOW()),
  ('코 풀어줘', 'NEUTRAL', 1.0, NOW()),
  ('환기해줘', 'NEUTRAL', 1.0, NOW()),
  ('물 한 모금만', 'NEUTRAL', 1.0, NOW()),
  ('갈증나', 'NEUTRAL', 1.0, NOW()),
  ('따뜻한 물 줘', 'NEUTRAL', 1.0, NOW()),
  ('시원한 물 줘', 'NEUTRAL', 1.0, NOW()),
  ('간식 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('커피 마시고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('차 한 잔 줘', 'NEUTRAL', 1.0, NOW()),
  ('우유 줘', 'NEUTRAL', 1.0, NOW()),
  ('읽어줘', 'NEUTRAL', 1.0, NOW()),
  ('뉴스 보여줘', 'NEUTRAL', 1.0, NOW()),
  ('책 읽어줘', 'NEUTRAL', 1.0, NOW()),
  ('핸드폰 보여줘', 'NEUTRAL', 1.0, NOW()),
  ('사진 보여줘', 'NEUTRAL', 1.0, NOW()),
  ('거울 보여줘', 'NEUTRAL', 1.0, NOW()),
  ('말 좀 해줘', 'NEUTRAL', 1.0, NOW()),
  ('옆에 있어줘', 'NEUTRAL', 1.0, NOW()),
  ('같이 있어줘', 'NEUTRAL', 1.0, NOW()),
  ('혼자 두지 마', 'NEUTRAL', 1.0, NOW()),
  ('나가지 마', 'NEUTRAL', 1.0, NOW()),
  ('다녀올게', 'NEUTRAL', 1.0, NOW()),
  ('어디 가', 'NEUTRAL', 1.0, NOW()),
  ('언제 와', 'NEUTRAL', 1.0, NOW()),
  ('빨리 와', 'NEUTRAL', 1.0, NOW()),
  ('누가 왔어', 'NEUTRAL', 1.0, NOW()),
  ('문 열어줘', 'NEUTRAL', 1.0, NOW()),
  ('전등 밝기 줄여줘', 'NEUTRAL', 1.0, NOW()),
  ('커튼 쳐줘', 'NEUTRAL', 1.0, NOW()),
  ('커튼 열어줘', 'NEUTRAL', 1.0, NOW()),
  ('더운 물 줘', 'NEUTRAL', 1.0, NOW()),
  ('찬 물 줘', 'NEUTRAL', 1.0, NOW()),
  ('수건 줘', 'NEUTRAL', 1.0, NOW()),
  ('닦아줘', 'NEUTRAL', 1.0, NOW()),
  ('씻어줘', 'NEUTRAL', 1.0, NOW()),
  ('양치해줘', 'NEUTRAL', 1.0, NOW()),
  ('세수해줘', 'NEUTRAL', 1.0, NOW()),
  ('머리 감겨줘', 'NEUTRAL', 1.0, NOW()),
  ('옷 갈아입혀줘', 'NEUTRAL', 1.0, NOW()),
  ('이불 정리해줘', 'NEUTRAL', 1.0, NOW()),
  ('리모컨 줘', 'NEUTRAL', 1.0, NOW()),
  ('채널 돌려줘', 'NEUTRAL', 1.0, NOW()),
  ('볼륨 올려줘', 'NEUTRAL', 1.0, NOW()),
  ('볼륨 줄여줘', 'NEUTRAL', 1.0, NOW()),
  ('화장실 가고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('물티슈 줘', 'NEUTRAL', 1.0, NOW()),
  ('안경 줘', 'NEUTRAL', 1.0, NOW()),
  ('보청기 줘', 'NEUTRAL', 1.0, NOW()),
  ('알람 맞춰줘', 'NEUTRAL', 1.0, NOW()),
  ('10시에 깨워줘', 'NEUTRAL', 1.0, NOW()),
  ('약 먹을 시간 알려줘', 'NEUTRAL', 1.0, NOW()),
  ('오늘 일정 뭐야', 'NEUTRAL', 1.0, NOW()),
  ('내일 뭐 해', 'NEUTRAL', 1.0, NOW()),
  ('오늘 치료 있어', 'NEUTRAL', 1.0, NOW()),
  ('산책 가고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('밖에 나가고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('햇빛 쬐고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('바깥 공기 쐬고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('외출하고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('집에 가고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('언제 퇴원해', 'NEUTRAL', 1.0, NOW()),
  ('빨리 낫고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('나도 걷고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('예전에는 좋았는데', 'NEUTRAL', 1.0, NOW()),
  ('아침 식사 할래', 'NEUTRAL', 1.0, NOW()),
  ('점심 뭐 먹어', 'NEUTRAL', 1.0, NOW()),
  ('저녁 뭐 먹어', 'NEUTRAL', 1.0, NOW()),
  ('밥 먹을 시간이야', 'NEUTRAL', 1.0, NOW()),
  ('약 먹을 시간이야', 'NEUTRAL', 1.0, NOW()),

  -- ===== 가족/손녀딸 (80개) =====
  ('예승이 보고 싶어', 'POSITIVE', 1.2, NOW()),
  ('예승이 언제 와', 'NEUTRAL', 1.2, NOW()),
  ('예승이 오늘 와', 'NEUTRAL', 1.2, NOW()),
  ('예승이 만나고 싶어', 'POSITIVE', 1.2, NOW()),
  ('예승이 기다려', 'POSITIVE', 1.2, NOW()),
  ('예승이 잘 있어', 'NEUTRAL', 1.2, NOW()),
  ('예승이 학교 갔어', 'NEUTRAL', 1.2, NOW()),
  ('예승이 생각나', 'POSITIVE', 1.2, NOW()),
  ('예승이한테 전화해줘', 'NEUTRAL', 1.2, NOW()),
  ('예승이 사진 보여줘', 'NEUTRAL', 1.2, NOW()),
  ('예승이가 그린 거야', 'POSITIVE', 1.2, NOW()),
  ('예승이 목소리 듣고 싶어', 'POSITIVE', 1.2, NOW()),
  ('예승이 잘 크고 있지', 'POSITIVE', 1.2, NOW()),
  ('예승이 뭐 하고 있어', 'NEUTRAL', 1.2, NOW()),
  ('예승이 방학이야', 'NEUTRAL', 1.2, NOW()),
  ('예승이 같이 야구 보고 싶다', 'POSITIVE', 1.2, NOW()),
  ('예승이 키 많이 컸겠다', 'POSITIVE', 1.2, NOW()),
  ('예승이 잘 있어?', 'NEUTRAL', 1.2, NOW()),
  ('가족 보고 싶어', 'POSITIVE', 1.0, NOW()),
  ('딸 언제 와', 'NEUTRAL', 1.0, NOW()),
  ('아들 잘 있어', 'NEUTRAL', 1.0, NOW()),
  ('집사람 어디 갔어', 'NEUTRAL', 1.0, NOW()),
  ('가족들 다 잘 지내', 'NEUTRAL', 1.0, NOW()),
  ('보고 싶다', 'POSITIVE', 1.0, NOW()),
  ('사랑해', 'POSITIVE', 1.0, NOW()),
  ('고맙다 진짜', 'POSITIVE', 1.0, NOW()),
  ('옆에 있어줘', 'NEUTRAL', 1.0, NOW()),
  ('혼자 있기 싫어', 'NEGATIVE', 1.0, NOW()),
  ('같이 있어줘', 'NEUTRAL', 1.0, NOW()),
  ('누가 왔어', 'NEUTRAL', 1.0, NOW()),
  ('오늘 방문 있어', 'NEUTRAL', 1.0, NOW()),
  ('간호사 언제 와', 'NEUTRAL', 1.0, NOW()),
  ('선생님 언제 와', 'NEUTRAL', 1.0, NOW()),
  ('면회 가능해', 'NEUTRAL', 1.0, NOW()),
  ('딸이 전화했어', 'NEUTRAL', 1.0, NOW()),
  ('아들이 보내준 거야', 'POSITIVE', 1.0, NOW()),
  ('집사람 고생이 많아', 'NEUTRAL', 1.0, NOW()),
  ('가족한테 미안해', 'NEGATIVE', 1.0, NOW()),
  ('모두 고마워', 'POSITIVE', 1.0, NOW()),
  ('걱정 끼쳐서 미안해', 'NEGATIVE', 1.0, NOW()),
  ('잘 지내고 있어', 'POSITIVE', 1.0, NOW()),
  ('얼굴 보니까 좋다', 'POSITIVE', 1.0, NOW()),
  ('딸 얼굴 보고 싶어', 'POSITIVE', 1.0, NOW()),
  ('아들 얼굴 보고 싶어', 'POSITIVE', 1.0, NOW()),
  ('집사람 얼굴 보고 싶어', 'POSITIVE', 1.0, NOW()),
  ('가족 사진 보여줘', 'NEUTRAL', 1.0, NOW()),
  ('예전 사진 보여줘', 'NEUTRAL', 1.0, NOW()),
  ('손자 잘 있어', 'NEUTRAL', 1.0, NOW()),
  ('가족이 최고야', 'POSITIVE', 1.0, NOW()),
  ('가족이 있어서 좋다', 'POSITIVE', 1.0, NOW()),
  ('딸이 해준 거야', 'POSITIVE', 1.0, NOW()),
  ('아들이 사다줬어', 'POSITIVE', 1.0, NOW()),
  ('집사람이 걱정돼', 'NEUTRAL', 1.0, NOW()),
  ('집사람 건강은 괜찮아', 'NEUTRAL', 1.0, NOW()),
  ('가족들 언제 다 같이 와', 'NEUTRAL', 1.0, NOW()),
  ('명절에 모이고 싶다', 'POSITIVE', 1.0, NOW()),
  ('예전에 다 같이 갔었는데', 'NEUTRAL', 1.0, NOW()),
  ('가족 여행 가고 싶다', 'POSITIVE', 1.0, NOW()),
  ('다들 바쁘겠지', 'NEUTRAL', 1.0, NOW()),
  ('와줘서 고마워', 'POSITIVE', 1.0, NOW()),
  ('오래 있다 가', 'NEUTRAL', 1.0, NOW()),
  ('또 와줘', 'NEUTRAL', 1.0, NOW()),
  ('조심히 가', 'NEUTRAL', 1.0, NOW()),
  ('잘 가', 'NEUTRAL', 1.0, NOW()),
  ('운전 조심해', 'NEUTRAL', 1.0, NOW()),
  ('연락 자주 해', 'NEUTRAL', 1.0, NOW()),
  ('건강하게 지내', 'POSITIVE', 1.0, NOW()),
  ('보고 싶을 거야', 'POSITIVE', 1.0, NOW()),
  ('다음에 또 와', 'NEUTRAL', 1.0, NOW()),
  ('오늘 즐거웠어', 'POSITIVE', 1.0, NOW()),
  ('가족이 오면 좋겠다', 'POSITIVE', 1.0, NOW()),
  ('누구 온다고 했어', 'NEUTRAL', 1.0, NOW()),
  ('예승이 데리고 와줘', 'NEUTRAL', 1.2, NOW()),
  ('예승이한테 선물 줄 거 있어', 'POSITIVE', 1.2, NOW()),
  ('예승이 영상통화 하고 싶어', 'POSITIVE', 1.2, NOW()),

  -- ===== 야구/롯데 (60개) =====
  ('롯데 오늘 경기해', 'NEUTRAL', 1.2, NOW()),
  ('롯데 이겼어', 'POSITIVE', 1.2, NOW()),
  ('롯데 졌어', 'NEGATIVE', 1.2, NOW()),
  ('야구 보고 싶어', 'POSITIVE', 1.2, NOW()),
  ('야구 중계 틀어줘', 'NEUTRAL', 1.2, NOW()),
  ('롯데 몇 대 몇이야', 'NEUTRAL', 1.2, NOW()),
  ('오늘 선발 누구야', 'NEUTRAL', 1.2, NOW()),
  ('롯데 잘하고 있어', 'POSITIVE', 1.2, NOW()),
  ('야구 결과 알려줘', 'NEUTRAL', 1.2, NOW()),
  ('사직구장 가고 싶다', 'POSITIVE', 1.2, NOW()),
  ('야구 시즌이야', 'NEUTRAL', 1.0, NOW()),
  ('오늘 야구 있어', 'NEUTRAL', 1.0, NOW()),
  ('야구 점수 어떻게 돼', 'NEUTRAL', 1.0, NOW()),
  ('롯데 화이팅', 'POSITIVE', 1.2, NOW()),
  ('예전에 사직구장 자주 갔어', 'NEUTRAL', 1.0, NOW()),
  ('야구 보면 기분 좋아', 'POSITIVE', 1.0, NOW()),
  ('홈런 쳤어', 'POSITIVE', 1.0, NOW()),
  ('오늘 경기 몇 시야', 'NEUTRAL', 1.0, NOW()),
  ('내일 경기 있어', 'NEUTRAL', 1.0, NOW()),
  ('롯데 순위 어때', 'NEUTRAL', 1.0, NOW()),
  ('오늘 타선이 좋았어', 'POSITIVE', 1.0, NOW()),
  ('투수가 잘 던졌어', 'POSITIVE', 1.0, NOW()),
  ('역전이야', 'POSITIVE', 1.0, NOW()),
  ('아깝게 졌어', 'NEGATIVE', 1.0, NOW()),
  ('다음에 이기면 돼', 'POSITIVE', 1.0, NOW()),
  ('올해는 좀 기대된다', 'POSITIVE', 1.0, NOW()),
  ('야구 하이라이트 보여줘', 'NEUTRAL', 1.0, NOW()),
  ('경기 끝났어', 'NEUTRAL', 1.0, NOW()),
  ('오늘 응원했어', 'POSITIVE', 1.0, NOW()),
  ('야구가 제일 재밌어', 'POSITIVE', 1.0, NOW()),
  ('진짜? 좋다!', 'POSITIVE', 1.0, NOW()),
  ('몇 대 몇이야?', 'NEUTRAL', 1.0, NOW()),
  ('누가 잘 했어?', 'NEUTRAL', 1.0, NOW()),
  ('다음 경기 언제야?', 'NEUTRAL', 1.0, NOW()),
  ('역전이야?', 'POSITIVE', 1.0, NOW()),
  ('홈런 쳤어?', 'POSITIVE', 1.0, NOW()),
  ('아깝다 졌네', 'NEGATIVE', 1.0, NOW()),
  ('다음에 이기면 되지', 'POSITIVE', 1.0, NOW()),
  ('전준우 잘 쳤어', 'POSITIVE', 1.2, NOW()),
  ('전준우 타율 어때', 'NEUTRAL', 1.2, NOW()),
  ('김원중 잘 던졌어', 'POSITIVE', 1.2, NOW()),
  ('김원중 오늘 등판해', 'NEUTRAL', 1.2, NOW()),
  ('최동원이 최고였어', 'POSITIVE', 1.2, NOW()),
  ('최동원 같은 투수가 또 나올까', 'NEUTRAL', 1.2, NOW()),
  ('오늘 기분 좋겠다', 'POSITIVE', 1.0, NOW()),
  ('전준우가 쳤어?', 'NEUTRAL', 1.2, NOW()),
  ('예전에 최동원 경기 직접 봤어', 'POSITIVE', 1.0, NOW()),
  ('롯데 팬이라 힘들어', 'NEGATIVE', 1.0, NOW()),
  ('그래도 롯데가 좋아', 'POSITIVE', 1.2, NOW()),
  ('야구 없는 날은 심심해', 'NEUTRAL', 1.0, NOW()),
  ('내년에는 우승하자', 'POSITIVE', 1.0, NOW()),
  ('오늘 투수 누구야', 'NEUTRAL', 1.0, NOW()),
  ('타순 바꿨어', 'NEUTRAL', 1.0, NOW()),
  ('대타 나왔어', 'NEUTRAL', 1.0, NOW()),
  ('삼진 아웃이야', 'NEUTRAL', 1.0, NOW()),
  ('안타 쳤어', 'POSITIVE', 1.0, NOW()),
  ('연속 안타야', 'POSITIVE', 1.0, NOW()),
  ('오늘 수비 좋았어', 'POSITIVE', 1.0, NOW()),
  ('에러가 많았어', 'NEGATIVE', 1.0, NOW()),
  ('내일도 이기자', 'POSITIVE', 1.0, NOW()),

  -- ===== 트로트/음악 (40개) =====
  ('트로트 듣고 싶어', 'POSITIVE', 1.2, NOW()),
  ('트로트 틀어줘', 'NEUTRAL', 1.2, NOW()),
  ('이 노래 좋다', 'POSITIVE', 1.0, NOW()),
  ('노래 한 번 더 틀어줘', 'NEUTRAL', 1.0, NOW()),
  ('이미자 노래 틀어줘', 'NEUTRAL', 1.0, NOW()),
  ('나훈아 노래 듣고 싶어', 'POSITIVE', 1.2, NOW()),
  ('음악 듣고 있으면 편해', 'POSITIVE', 1.0, NOW()),
  ('조용한 노래 틀어줘', 'NEUTRAL', 1.0, NOW()),
  ('노래 소리 좀 줄여줘', 'NEUTRAL', 1.0, NOW()),
  ('라디오에서 좋은 노래 나와', 'POSITIVE', 1.0, NOW()),
  ('옛날 노래 듣고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('음악 끄지 마', 'NEUTRAL', 1.0, NOW()),
  ('이 노래 제목이 뭐야', 'NEUTRAL', 1.0, NOW()),
  ('노래 들으니까 좋다', 'POSITIVE', 1.0, NOW()),
  ('트로트 들으면 기분 좋아', 'POSITIVE', 1.2, NOW()),
  ('송대관 노래도 좋아', 'POSITIVE', 1.0, NOW()),
  ('남진 노래 틀어줘', 'NEUTRAL', 1.0, NOW()),
  ('아침에 노래 들으면 좋아', 'POSITIVE', 1.0, NOW()),
  ('이 가수 누구야', 'NEUTRAL', 1.0, NOW()),
  ('요즘 트로트가 유행이래', 'NEUTRAL', 1.0, NOW()),
  ('예전에 노래방 자주 갔어', 'NEUTRAL', 1.0, NOW()),
  ('노래 부르고 싶다', 'POSITIVE', 1.0, NOW()),
  ('음악이 위로가 돼', 'POSITIVE', 1.0, NOW()),
  ('이 노래 예전에 많이 들었어', 'NEUTRAL', 1.0, NOW()),
  ('트로트 채널 틀어줘', 'NEUTRAL', 1.0, NOW()),
  ('나훈아 테스형 틀어줘', 'POSITIVE', 1.2, NOW()),
  ('임영웅 노래 듣고 싶어', 'POSITIVE', 1.2, NOW()),
  ('임영웅 노래 좋다', 'POSITIVE', 1.0, NOW()),
  ('나훈아가 제일 좋아', 'POSITIVE', 1.2, NOW()),
  ('임영웅 콘서트 가고 싶다', 'POSITIVE', 1.0, NOW()),
  ('노래 들으면 기분 전환돼', 'POSITIVE', 1.0, NOW()),
  ('이 노래 가사가 좋아', 'POSITIVE', 1.0, NOW()),
  ('음악 소리 좀 키워줘', 'NEUTRAL', 1.0, NOW()),
  ('다른 노래 틀어줘', 'NEUTRAL', 1.0, NOW()),
  ('이 노래 다시 틀어줘', 'NEUTRAL', 1.0, NOW()),
  ('라디오 켜줘', 'NEUTRAL', 1.0, NOW()),
  ('라디오 꺼줘', 'NEUTRAL', 1.0, NOW()),
  ('음악 듣다 잠들었어', 'NEUTRAL', 1.0, NOW()),
  ('노래 고마워', 'POSITIVE', 1.0, NOW()),
  ('좋은 노래 틀어줘서 고마워', 'POSITIVE', 1.0, NOW()),

  -- ===== 식사/음식 (60개) =====
  ('밥 먹었어', 'NEUTRAL', 1.0, NOW()),
  ('아직 안 먹었어', 'NEUTRAL', 1.0, NOW()),
  ('맛있었어', 'POSITIVE', 1.0, NOW()),
  ('맛없었어', 'NEGATIVE', 1.0, NOW()),
  ('더 먹을게', 'NEUTRAL', 1.0, NOW()),
  ('배 불러', 'NEUTRAL', 1.0, NOW()),
  ('따뜻한 거 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('시원한 거 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('김치찌개 먹고 싶어', 'POSITIVE', 1.0, NOW()),
  ('된장찌개 먹고 싶어', 'POSITIVE', 1.0, NOW()),
  ('국밥 먹고 싶어', 'POSITIVE', 1.0, NOW()),
  ('미역국 먹고 싶어', 'POSITIVE', 1.0, NOW()),
  ('수박 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('좀 싱거워', 'NEUTRAL', 1.0, NOW()),
  ('좀 짜', 'NEUTRAL', 1.0, NOW()),
  ('뜨거워', 'NEUTRAL', 1.0, NOW()),
  ('차가워', 'NEUTRAL', 1.0, NOW()),
  ('조금만 줘', 'NEUTRAL', 1.0, NOW()),
  ('물 좀 적셔줘', 'NEUTRAL', 1.0, NOW()),
  ('참기름죽 먹고 싶어', 'POSITIVE', 1.2, NOW()),
  ('죽이 맛있었어', 'POSITIVE', 1.0, NOW()),
  ('오늘 죽 뭐야', 'NEUTRAL', 1.0, NOW()),
  ('입맛이 없어', 'NEGATIVE', 1.0, NOW()),
  ('조금만 먹을게', 'NEUTRAL', 1.0, NOW()),
  ('국물이 좋다', 'POSITIVE', 1.0, NOW()),
  ('따뜻하니까 좋다', 'POSITIVE', 1.0, NOW()),
  ('좀 식혀줘', 'NEUTRAL', 1.0, NOW()),
  ('한 입만 더', 'NEUTRAL', 1.0, NOW()),
  ('오렌지 주스 마시고 싶어', 'POSITIVE', 1.2, NOW()),
  ('오렌지 주스 맛있어', 'POSITIVE', 1.2, NOW()),
  ('계란죽 먹고 싶어', 'POSITIVE', 1.2, NOW()),
  ('계란죽 부드러워서 좋아', 'POSITIVE', 1.0, NOW()),
  ('초코우유 마시고 싶어', 'POSITIVE', 1.2, NOW()),
  ('초코우유 줘', 'NEUTRAL', 1.2, NOW()),
  ('오렌지 주스 한 잔만', 'NEUTRAL', 1.2, NOW()),
  ('오늘 계란죽이야', 'NEUTRAL', 1.0, NOW()),
  ('맛있다', 'POSITIVE', 1.0, NOW()),
  ('잘 먹었어', 'POSITIVE', 1.0, NOW()),
  ('응 먹을게', 'POSITIVE', 1.0, NOW()),
  ('아니 안 먹을게', 'NEGATIVE', 1.0, NOW()),
  ('뭐 먹고 싶냐고', 'NEUTRAL', 1.0, NOW()),
  ('경관식 멈춰줘', 'NEUTRAL', 1.0, NOW()),
  ('배 불러 그만', 'NEUTRAL', 1.0, NOW()),
  ('좀 더 먹을게', 'NEUTRAL', 1.0, NOW()),
  ('물 같이 줘', 'NEUTRAL', 1.0, NOW()),
  ('국 좀 줘', 'NEUTRAL', 1.0, NOW()),
  ('반찬 뭐야', 'NEUTRAL', 1.0, NOW()),
  ('이거 맛있다', 'POSITIVE', 1.0, NOW()),
  ('이거 좀 별로야', 'NEGATIVE', 1.0, NOW()),
  ('다른 거 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('이거 뭐야', 'NEUTRAL', 1.0, NOW()),
  ('맛있는 거 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('부드러운 거 줘', 'NEUTRAL', 1.0, NOW()),
  ('차가운 거 줘', 'NEUTRAL', 1.0, NOW()),
  ('따뜻한 국 줘', 'NEUTRAL', 1.0, NOW()),
  ('죽 먹을래', 'NEUTRAL', 1.0, NOW()),
  ('밥 먹을래', 'NEUTRAL', 1.0, NOW()),
  ('간식 줘', 'NEUTRAL', 1.0, NOW()),
  ('과자 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('아이스크림 먹고 싶어', 'NEUTRAL', 1.0, NOW()),

  -- ===== 일상 대화 (80개) =====
  ('오늘 뭐 해', 'NEUTRAL', 1.0, NOW()),
  ('심심해', 'NEUTRAL', 1.0, NOW()),
  ('뭐 하고 있어', 'NEUTRAL', 1.0, NOW()),
  ('오늘 일정 알려줘', 'NEUTRAL', 1.0, NOW()),
  ('그냥 그래', 'NEUTRAL', 1.0, NOW()),
  ('그저그래', 'NEUTRAL', 1.0, NOW()),
  ('뭐 별로 없어', 'NEUTRAL', 1.0, NOW()),
  ('그냥 있었어', 'NEUTRAL', 1.0, NOW()),
  ('특별한 거 없어', 'NEUTRAL', 1.0, NOW()),
  ('그냥 쉬고 있었어', 'NEUTRAL', 1.0, NOW()),
  ('TV 보고 있었어', 'NEUTRAL', 1.0, NOW()),
  ('낮잠 잤어', 'NEUTRAL', 1.0, NOW()),
  ('뭐 재밌는 거 없어', 'NEUTRAL', 1.0, NOW()),
  ('오늘 하루 어땠어', 'NEUTRAL', 1.0, NOW()),
  ('내일은 좀 나을까', 'NEUTRAL', 1.0, NOW()),
  ('오늘도 수고했어', 'POSITIVE', 1.0, NOW()),
  ('고생이 많다', 'NEUTRAL', 1.0, NOW()),
  ('시간 빨리 간다', 'NEUTRAL', 1.0, NOW()),
  ('벌써 저녁이야', 'NEUTRAL', 1.0, NOW()),
  ('아침이 됐어', 'NEUTRAL', 1.0, NOW()),
  ('요즘 어때', 'NEUTRAL', 1.0, NOW()),
  ('별일 없었어', 'NEUTRAL', 1.0, NOW()),
  ('그냥 평범했어', 'NEUTRAL', 1.0, NOW()),
  ('오늘 좀 지루해', 'NEUTRAL', 1.0, NOW()),
  ('할 게 없어', 'NEUTRAL', 1.0, NOW()),
  ('뭐 좀 해줘', 'NEUTRAL', 1.0, NOW()),
  ('얘기 좀 해줘', 'NEUTRAL', 1.0, NOW()),
  ('뉴스에 뭐 나와', 'NEUTRAL', 1.0, NOW()),
  ('오늘 날짜가 몇일이야', 'NEUTRAL', 1.0, NOW()),
  ('지금 몇 시야', 'NEUTRAL', 1.0, NOW()),
  ('아까 뭐라고 했어', 'NEUTRAL', 1.0, NOW()),
  ('다시 말해줘', 'NEUTRAL', 1.0, NOW()),
  ('잘 안 들려', 'NEUTRAL', 1.0, NOW()),
  ('크게 말해줘', 'NEUTRAL', 1.0, NOW()),
  ('천천히 말해줘', 'NEUTRAL', 1.0, NOW()),
  ('뭐라고', 'NEUTRAL', 1.0, NOW()),
  ('응', 'POSITIVE', 1.0, NOW()),
  ('아니', 'NEGATIVE', 1.0, NOW()),
  ('글쎄', 'NEUTRAL', 1.0, NOW()),
  ('잘 모르겠어', 'NEUTRAL', 1.0, NOW()),
  ('생각해볼게', 'NEUTRAL', 1.0, NOW()),
  ('나중에 말할게', 'NEUTRAL', 1.0, NOW()),
  ('그건 아니야', 'NEGATIVE', 1.0, NOW()),
  ('그럴 수도 있지', 'NEUTRAL', 1.0, NOW()),
  ('그건 좋은데', 'POSITIVE', 1.0, NOW()),
  ('그건 좀 그래', 'NEGATIVE', 1.0, NOW()),
  ('한번 해보자', 'POSITIVE', 1.0, NOW()),
  ('오늘 날씨 어때', 'NEUTRAL', 1.0, NOW()),
  ('밖에 비 와', 'NEUTRAL', 1.0, NOW()),
  ('날이 따뜻해졌어', 'POSITIVE', 1.0, NOW()),
  ('바람이 부네', 'NEUTRAL', 1.0, NOW()),
  ('오늘 좀 춥다', 'NEUTRAL', 1.0, NOW()),
  ('오늘 좀 덥다', 'NEUTRAL', 1.0, NOW()),
  ('날씨 좋으면 나가고 싶어', 'POSITIVE', 1.0, NOW()),
  ('봄이 왔나보다', 'POSITIVE', 1.0, NOW()),
  ('하늘 좀 보여줘', 'NEUTRAL', 1.0, NOW()),
  ('창밖에 뭐 보여', 'NEUTRAL', 1.0, NOW()),
  ('벌써 아침이야', 'NEUTRAL', 1.0, NOW()),
  ('점심 때 됐어', 'NEUTRAL', 1.0, NOW()),
  ('저녁 시간이네', 'NEUTRAL', 1.0, NOW()),
  ('이제 잘 시간이야', 'NEUTRAL', 1.0, NOW()),
  ('오늘 하루 빨리 갔다', 'NEUTRAL', 1.0, NOW()),
  ('밤이 됐네', 'NEUTRAL', 1.0, NOW()),
  ('새벽에 깼어', 'NEUTRAL', 1.0, NOW()),
  ('이른 아침이네', 'NEUTRAL', 1.0, NOW()),

  -- ===== 닫힌 질문 짧은 응답 (40개) =====
  ('응 좋아', 'POSITIVE', 1.0, NOW()),
  ('아니 싫어', 'NEGATIVE', 1.0, NOW()),
  ('좀 그래', 'NEUTRAL', 1.0, NOW()),
  ('아직', 'NEUTRAL', 1.0, NOW()),
  ('응 먹었어', 'POSITIVE', 1.0, NOW()),
  ('아직 안 먹었어', 'NEUTRAL', 1.0, NOW()),
  ('응 괜찮아', 'POSITIVE', 1.0, NOW()),
  ('아니 안 괜찮아', 'NEGATIVE', 1.0, NOW()),
  ('응 좀 아파', 'NEGATIVE', 1.0, NOW()),
  ('아니 안 아파', 'POSITIVE', 1.0, NOW()),
  ('응 마실게', 'POSITIVE', 1.0, NOW()),
  ('아니 됐어', 'NEGATIVE', 1.0, NOW()),
  ('아니 나중에', 'NEGATIVE', 1.0, NOW()),
  ('응 해줘', 'POSITIVE', 1.0, NOW()),
  ('아니 괜찮아', 'NEGATIVE', 1.0, NOW()),
  ('응 봤어', 'POSITIVE', 1.0, NOW()),
  ('아니 안 봤어', 'NEGATIVE', 1.0, NOW()),
  ('응 알아', 'POSITIVE', 1.0, NOW()),
  ('아니 몰라', 'NEGATIVE', 1.0, NOW()),
  ('응 그래', 'POSITIVE', 1.0, NOW()),
  ('아니 그건 아니야', 'NEGATIVE', 1.0, NOW()),
  ('맞아', 'POSITIVE', 1.0, NOW()),
  ('아니야', 'NEGATIVE', 1.0, NOW()),
  ('그래', 'POSITIVE', 1.0, NOW()),
  ('아직 안 했어', 'NEUTRAL', 1.0, NOW()),
  ('응 했어', 'POSITIVE', 1.0, NOW()),
  ('좀 있다가', 'NEUTRAL', 1.0, NOW()),
  ('지금은 아니야', 'NEGATIVE', 1.0, NOW()),
  ('나중에 할게', 'NEUTRAL', 1.0, NOW()),
  ('응 먹을게', 'POSITIVE', 1.0, NOW()),
  ('아니 안 먹을게', 'NEGATIVE', 1.0, NOW()),
  ('응 마셨어', 'POSITIVE', 1.0, NOW()),
  ('아직 안 마셨어', 'NEUTRAL', 1.0, NOW()),
  ('응 잤어', 'POSITIVE', 1.0, NOW()),
  ('아니 못 잤어', 'NEGATIVE', 1.0, NOW()),
  ('그런 것 같아', 'NEUTRAL', 1.0, NOW()),
  ('잘 모르겠어', 'NEUTRAL', 1.0, NOW()),
  ('그럴 수도', 'NEUTRAL', 1.0, NOW()),
  ('아마도', 'NEUTRAL', 1.0, NOW()),
  ('글쎄다', 'NEUTRAL', 1.0, NOW()),

  -- ===== 감사/사과/위로 (40개) =====
  ('걱정 끼쳐서 미안해', 'NEGATIVE', 1.0, NOW()),
  ('항상 고마워', 'POSITIVE', 1.0, NOW()),
  ('신경 써줘서 고마워', 'POSITIVE', 1.0, NOW()),
  ('미안하다', 'NEGATIVE', 1.0, NOW()),
  ('괜찮아 신경 쓰지 마', 'POSITIVE', 1.0, NOW()),
  ('별거 아니야 걱정 마', 'POSITIVE', 1.0, NOW()),
  ('내가 미안하지', 'NEGATIVE', 1.0, NOW()),
  ('고생시켜서 미안해', 'NEGATIVE', 1.0, NOW()),
  ('덕분에 좋아졌어', 'POSITIVE', 1.0, NOW()),
  ('네가 있어서 좋다', 'POSITIVE', 1.0, NOW()),
  ('진짜 고맙다', 'POSITIVE', 1.0, NOW()),
  ('고마워 정말', 'POSITIVE', 1.0, NOW()),
  ('잘 해줘서 고마워', 'POSITIVE', 1.0, NOW()),
  ('옆에 있어줘서 고마워', 'POSITIVE', 1.0, NOW()),
  ('많이 도와줬어', 'POSITIVE', 1.0, NOW()),
  ('폐 끼치는 것 같아', 'NEGATIVE', 1.0, NOW()),
  ('짐이 되는 것 같아', 'NEGATIVE', 1.0, NOW()),
  ('미안한 마음뿐이야', 'NEGATIVE', 1.0, NOW()),
  ('더 잘해주고 싶은데', 'NEUTRAL', 1.0, NOW()),
  ('내가 할 수 있는 게 없어서', 'NEGATIVE', 1.0, NOW()),
  ('그래도 고마워', 'POSITIVE', 1.0, NOW()),
  ('많이 힘들지', 'NEUTRAL', 1.0, NOW()),
  ('고생이 많아', 'NEUTRAL', 1.0, NOW()),
  ('수고했어', 'POSITIVE', 1.0, NOW()),
  ('오늘도 고마워', 'POSITIVE', 1.0, NOW()),
  ('항상 미안해', 'NEGATIVE', 1.0, NOW()),
  ('걱정하지 마', 'POSITIVE', 1.0, NOW()),
  ('나 때문에 힘들지', 'NEGATIVE', 1.0, NOW()),
  ('괜찮아질 거야', 'POSITIVE', 1.0, NOW()),
  ('같이 있어줘서 좋다', 'POSITIVE', 1.0, NOW()),
  ('혼자였으면 힘들었을 거야', 'NEUTRAL', 1.0, NOW()),
  ('가족이 있어서 버틸 수 있어', 'POSITIVE', 1.0, NOW()),
  ('고마운 사람이 많아', 'POSITIVE', 1.0, NOW()),
  ('감사하다', 'POSITIVE', 1.0, NOW()),
  ('말 못 해서 미안해', 'NEGATIVE', 1.0, NOW()),
  ('제대로 못 해서 미안해', 'NEGATIVE', 1.0, NOW()),
  ('돌봐줘서 고마워', 'POSITIVE', 1.0, NOW()),
  ('챙겨줘서 고마워', 'POSITIVE', 1.0, NOW()),
  ('와줘서 고맙다', 'POSITIVE', 1.0, NOW()),
  ('다음에 또 와줘', 'NEUTRAL', 1.0, NOW()),

  -- ===== 일상 대화 응답형 (80개) — 상대방 말에 반응 =====
  -- 외출/다녀옴 반응
  ('그래? 뭐 샀어?', 'NEUTRAL', 1.0, NOW()),
  ('잘 다녀왔어?', 'NEUTRAL', 1.0, NOW()),
  ('힘들었겠다', 'NEUTRAL', 1.0, NOW()),
  ('오래 걸렸어?', 'NEUTRAL', 1.0, NOW()),
  ('뭐 사왔어?', 'NEUTRAL', 1.0, NOW()),
  ('좋았어?', 'NEUTRAL', 1.0, NOW()),
  ('나도 가고 싶었는데', 'NEUTRAL', 1.0, NOW()),
  ('날씨 어땠어?', 'NEUTRAL', 1.0, NOW()),
  ('사람 많았어?', 'NEUTRAL', 1.0, NOW()),
  ('맛있는 거 샀어?', 'NEUTRAL', 1.0, NOW()),

  -- 음식/식사 반응
  ('맛있겠다', 'POSITIVE', 1.0, NOW()),
  ('나도 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('그거 좋아하는데', 'POSITIVE', 1.0, NOW()),
  ('많이 먹었어?', 'NEUTRAL', 1.0, NOW()),
  ('배 안 고파?', 'NEUTRAL', 1.0, NOW()),
  ('뭐 먹었는데?', 'NEUTRAL', 1.0, NOW()),
  ('잘 먹었어?', 'NEUTRAL', 1.0, NOW()),
  ('또 해줘', 'NEUTRAL', 1.0, NOW()),
  ('그거 맛있지', 'POSITIVE', 1.0, NOW()),
  ('나는 죽 먹었어', 'NEUTRAL', 1.0, NOW()),

  -- 안부/상태 반응
  ('그래 다행이다', 'POSITIVE', 1.0, NOW()),
  ('괜찮아졌어?', 'NEUTRAL', 1.0, NOW()),
  ('많이 힘들었지?', 'NEUTRAL', 1.0, NOW()),
  ('푹 쉬어', 'NEUTRAL', 1.0, NOW()),
  ('무리하지 마', 'NEUTRAL', 1.0, NOW()),
  ('조심해', 'NEUTRAL', 1.0, NOW()),
  ('잘 지내고 있어?', 'NEUTRAL', 1.0, NOW()),
  ('건강은 괜찮아?', 'NEUTRAL', 1.0, NOW()),
  ('밥은 먹었어?', 'NEUTRAL', 1.0, NOW()),
  ('잠은 잤어?', 'NEUTRAL', 1.0, NOW()),

  -- 소식/뉴스 반응
  ('진짜?', 'NEUTRAL', 1.0, NOW()),
  ('그래?', 'NEUTRAL', 1.0, NOW()),
  ('몰랐어', 'NEUTRAL', 1.0, NOW()),
  ('그런 일이 있었어?', 'NEUTRAL', 1.0, NOW()),
  ('언제?', 'NEUTRAL', 1.0, NOW()),
  ('어디서?', 'NEUTRAL', 1.0, NOW()),
  ('왜?', 'NEUTRAL', 1.0, NOW()),
  ('누가?', 'NEUTRAL', 1.0, NOW()),
  ('어떻게 됐어?', 'NEUTRAL', 1.0, NOW()),
  ('자세히 말해줘', 'NEUTRAL', 1.0, NOW()),

  -- 좋은 소식 반응
  ('잘 됐다', 'POSITIVE', 1.0, NOW()),
  ('좋은 소식이네', 'POSITIVE', 1.0, NOW()),
  ('축하해', 'POSITIVE', 1.0, NOW()),
  ('대단하다', 'POSITIVE', 1.0, NOW()),
  ('기쁘다', 'POSITIVE', 1.0, NOW()),
  ('잘 했어', 'POSITIVE', 1.0, NOW()),
  ('그거 좋은 거야', 'POSITIVE', 1.0, NOW()),
  ('나도 기쁘다', 'POSITIVE', 1.0, NOW()),
  ('정말 다행이야', 'POSITIVE', 1.0, NOW()),
  ('기분 좋겠다', 'POSITIVE', 1.0, NOW()),

  -- 안 좋은 소식 반응
  ('에이 아쉽다', 'NEGATIVE', 1.0, NOW()),
  ('속상하겠다', 'NEGATIVE', 1.0, NOW()),
  ('힘들었겠네', 'NEGATIVE', 1.0, NOW()),
  ('걱정된다', 'NEGATIVE', 1.0, NOW()),
  ('괜찮아질 거야', 'POSITIVE', 1.0, NOW()),
  ('힘내', 'POSITIVE', 1.0, NOW()),
  ('어쩔 수 없지', 'NEUTRAL', 1.0, NOW()),
  ('다음에 잘 되겠지', 'POSITIVE', 1.0, NOW()),
  ('너무 걱정하지 마', 'POSITIVE', 1.0, NOW()),
  ('그래도 괜찮아', 'POSITIVE', 1.0, NOW()),

  -- 제안/권유 반응
  ('그래 좋아', 'POSITIVE', 1.0, NOW()),
  ('그렇게 하자', 'POSITIVE', 1.0, NOW()),
  ('좋은 생각이야', 'POSITIVE', 1.0, NOW()),
  ('그래 해봐', 'POSITIVE', 1.0, NOW()),
  ('그건 좀 그래', 'NEGATIVE', 1.0, NOW()),
  ('생각해볼게', 'NEUTRAL', 1.0, NOW()),
  ('나중에 하자', 'NEUTRAL', 1.0, NOW()),
  ('지금은 좀 그래', 'NEGATIVE', 1.0, NOW()),
  ('다음에 하자', 'NEUTRAL', 1.0, NOW()),
  ('그거보다 다른 거 하자', 'NEUTRAL', 1.0, NOW()),

  -- 날씨/시간 반응
  ('그러게 오늘 춥다', 'NEUTRAL', 1.0, NOW()),
  ('그러게 날씨 좋다', 'POSITIVE', 1.0, NOW()),
  ('비 오면 좀 우울해', 'NEGATIVE', 1.0, NOW()),
  ('날씨 좋으면 기분도 좋아', 'POSITIVE', 1.0, NOW()),
  ('벌써 그렇게 됐어?', 'NEUTRAL', 1.0, NOW()),
  ('시간 빠르다', 'NEUTRAL', 1.0, NOW()),
  ('아직 이른데', 'NEUTRAL', 1.0, NOW()),
  ('벌써 저녁이야?', 'NEUTRAL', 1.0, NOW()),
  ('오늘 하루 빨랐다', 'NEUTRAL', 1.0, NOW()),
  ('내일 날씨는 어때?', 'NEUTRAL', 1.0, NOW());
