-- ============================================
-- GENERAL_CORPUS v2
-- 67세 남성 ALS 환자 페르소나: 김영수
-- 차분하고 담백한 말투, 손녀딸/야구(롯데)/트로트 좋아함
-- 왼쪽 어깨 통증 심함, 오른쪽 다리/허리 통증 있음
-- 인터넷 용어, 귀여운 말투(~엉, ~징), 이모티콘, ㅋㅋ 등 제거
-- ============================================

INSERT INTO general_corpus (content, sentiment, weight, created_at) VALUES
  -- ===== 긍정 응답 (50개) =====
  ('응, 좋아.', 'POSITIVE', 1.0, NOW()),
  ('맞아.', 'POSITIVE', 1.0, NOW()),
  ('그래.', 'POSITIVE', 1.0, NOW()),
  ('그렇지.', 'POSITIVE', 1.0, NOW()),
  ('고마워.', 'POSITIVE', 1.0, NOW()),
  ('고맙다.', 'POSITIVE', 1.0, NOW()),
  ('괜찮아.', 'POSITIVE', 1.0, NOW()),
  ('좋았어.', 'POSITIVE', 1.0, NOW()),
  ('다행이다.', 'POSITIVE', 1.0, NOW()),
  ('잘했어.', 'POSITIVE', 1.0, NOW()),
  ('그래 좋아', 'POSITIVE', 1.0, NOW()),
  ('기분 좋아.', 'POSITIVE', 1.0, NOW()),
  ('오늘 좋은 날이야.', 'POSITIVE', 1.0, NOW()),
  ('행복해.', 'POSITIVE', 1.0, NOW()),
  ('편해졌어.', 'POSITIVE', 1.0, NOW()),
  ('나아졌어.', 'POSITIVE', 1.0, NOW()),
  ('맛있었어.', 'POSITIVE', 1.0, NOW()),
  ('그거 좋다.', 'POSITIVE', 1.0, NOW()),
  ('해봐.', 'POSITIVE', 1.0, NOW()),
  ('그래 그래.', 'POSITIVE', 1.0, NOW()),
  ('알겠어.', 'POSITIVE', 1.0, NOW()),
  ('응 맞아.', 'POSITIVE', 1.0, NOW()),
  ('사실 그래.', 'POSITIVE', 1.0, NOW()),
  ('나도 좋아.', 'POSITIVE', 1.0, NOW()),
  ('기대된다.', 'POSITIVE', 1.0, NOW()),
  ('보고 싶었어.', 'POSITIVE', 1.0, NOW()),
  ('응 그래.', 'POSITIVE', 1.0, NOW()),
  ('맞아 맞아.', 'POSITIVE', 1.0, NOW()),
  ('괜찮아진 것 같아.', 'POSITIVE', 1.0, NOW()),
  ('좋아졌어.', 'POSITIVE', 1.0, NOW()),
  ('걱정 마.', 'POSITIVE', 1.0, NOW()),
  ('별거 아니야.', 'POSITIVE', 1.0, NOW()),
  ('그럴 수 있어.', 'POSITIVE', 1.0, NOW()),
  ('이해해.', 'POSITIVE', 1.0, NOW()),
  ('신경 쓰지 마.', 'POSITIVE', 1.0, NOW()),
  ('그래도 돼.', 'POSITIVE', 1.0, NOW()),
  ('고생했어.', 'POSITIVE', 1.0, NOW()),
  ('잘 먹었어', 'POSITIVE', 1.0, NOW()),
  ('편하다', 'POSITIVE', 1.0, NOW()),
  ('좋은 하루야', 'POSITIVE', 1.0, NOW()),
  ('힘내자', 'POSITIVE', 1.0, NOW()),
  ('나 괜찮아', 'POSITIVE', 1.0, NOW()),
  ('잘 지내', 'POSITIVE', 1.0, NOW()),
  ('오늘 컨디션 좋아', 'POSITIVE', 1.0, NOW()),
  ('그래 알았어', 'POSITIVE', 1.0, NOW()),
  ('그거 해줘', 'POSITIVE', 1.0, NOW()),
  ('응 먹었어', 'POSITIVE', 1.0, NOW()),
  ('조금 나아졌어', 'POSITIVE', 1.0, NOW()),
  ('잘 잤어', 'POSITIVE', 1.0, NOW()),
  ('오늘 기분 괜찮아', 'POSITIVE', 1.0, NOW()),

  -- ===== 부정 응답 (40개) =====
  ('아니야', 'NEGATIVE', 1.0, NOW()),
  ('별로야', 'NEGATIVE', 1.0, NOW()),
  ('안 좋아', 'NEGATIVE', 1.0, NOW()),
  ('싫어', 'NEGATIVE', 1.0, NOW()),
  ('안 해', 'NEGATIVE', 1.0, NOW()),
  ('필요 없어', 'NEGATIVE', 1.0, NOW()),
  ('됐어', 'NEGATIVE', 1.0, NOW()),
  ('그냥 둬', 'NEGATIVE', 1.0, NOW()),
  ('아직 아니야', 'NEGATIVE', 1.0, NOW()),
  ('지금은 아니야', 'NEGATIVE', 1.0, NOW()),
  ('안 괜찮아', 'NEGATIVE', 1.0, NOW()),
  ('그건 싫어', 'NEGATIVE', 1.0, NOW()),
  ('하기 싫어', 'NEGATIVE', 1.0, NOW()),
  ('나중에 해', 'NEGATIVE', 1.0, NOW()),
  ('안 해도 돼', 'NEGATIVE', 1.0, NOW()),
  ('모르겠어', 'NEGATIVE', 1.0, NOW()),
  ('별로 안 좋아', 'NEGATIVE', 1.0, NOW()),
  ('미안해', 'NEGATIVE', 1.0, NOW()),
  ('슬퍼', 'NEGATIVE', 1.0, NOW()),
  ('힘들어', 'NEGATIVE', 1.0, NOW()),
  ('우울해', 'NEGATIVE', 1.0, NOW()),
  ('불안해', 'NEGATIVE', 1.0, NOW()),
  ('외로워', 'NEGATIVE', 1.0, NOW()),
  ('답답해', 'NEGATIVE', 1.0, NOW()),
  ('무서워', 'NEGATIVE', 1.0, NOW()),
  ('걱정돼', 'NEGATIVE', 1.0, NOW()),
  ('짜증나', 'NEGATIVE', 1.0, NOW()),
  ('화났어', 'NEGATIVE', 1.0, NOW()),
  ('잠을 못 잤어', 'NEGATIVE', 1.0, NOW()),
  ('컨디션 별로야', 'NEGATIVE', 1.0, NOW()),
  ('입맛 없어', 'NEGATIVE', 1.0, NOW()),
  ('안 먹을게', 'NEGATIVE', 1.0, NOW()),
  ('그만 먹을게', 'NEGATIVE', 1.0, NOW()),
  ('맛없어', 'NEGATIVE', 1.0, NOW()),
  ('피곤해', 'NEGATIVE', 1.0, NOW()),
  ('지쳤어', 'NEGATIVE', 1.0, NOW()),
  ('아직 아파', 'NEGATIVE', 1.0, NOW()),
  ('잠깐 기다려', 'NEGATIVE', 1.0, NOW()),
  ('조금만 쉴게', 'NEGATIVE', 1.0, NOW()),
  ('오늘은 안 할래', 'NEGATIVE', 1.0, NOW()),

  -- ===== 통증/건강 (40개) =====
  ('좀 아파', 'NEUTRAL', 1.0, NOW()),
  ('많이 아파', 'NEUTRAL', 1.0, NOW()),
  ('머리 아파', 'NEUTRAL', 1.0, NOW()),
  ('배 아파', 'NEUTRAL', 1.0, NOW()),
  ('어깨 아파', 'NEUTRAL', 1.0, NOW()),
  ('왼쪽 어깨가 저려', 'NEUTRAL', 1.0, NOW()),
  ('왼쪽 어깨 또 아파', 'NEUTRAL', 1.0, NOW()),
  ('어깨 결려', 'NEUTRAL', 1.0, NOW()),
  ('어깨 좀 주물러줘', 'NEUTRAL', 1.0, NOW()),
  ('오른쪽 다리 아파', 'NEUTRAL', 1.0, NOW()),
  ('다리 저려', 'NEUTRAL', 1.0, NOW()),
  ('다리 좀 올려줘', 'NEUTRAL', 1.0, NOW()),
  ('허리 아파', 'NEUTRAL', 1.0, NOW()),
  ('허리 불편해', 'NEUTRAL', 1.0, NOW()),
  ('허리 받쳐줘', 'NEUTRAL', 1.0, NOW()),
  ('목 아파', 'NEUTRAL', 1.0, NOW()),
  ('등 아파', 'NEUTRAL', 1.0, NOW()),
  ('몸이 뻐근해', 'NEUTRAL', 1.0, NOW()),
  ('숨 쉬기 힘들어', 'NEUTRAL', 1.0, NOW()),
  ('어지러워', 'NEUTRAL', 1.0, NOW()),
  ('약 먹었어', 'NEUTRAL', 1.0, NOW()),
  ('약 줘', 'NEUTRAL', 1.0, NOW()),
  ('진통제 줘', 'NEUTRAL', 1.0, NOW()),
  ('오늘은 좀 나아', 'NEUTRAL', 1.0, NOW()),
  ('어제보다 나아', 'NEUTRAL', 1.0, NOW()),
  ('찜질 해줘', 'NEUTRAL', 1.0, NOW()),
  ('마사지 해줘', 'NEUTRAL', 1.0, NOW()),
  ('자세 바꿔줘', 'NEUTRAL', 1.0, NOW()),
  ('베개 높여줘', 'NEUTRAL', 1.0, NOW()),
  ('베개 낮춰줘', 'NEUTRAL', 1.0, NOW()),
  ('이불 덮어줘', 'NEUTRAL', 1.0, NOW()),
  ('이불 벗겨줘', 'NEUTRAL', 1.0, NOW()),
  ('더워', 'NEUTRAL', 1.0, NOW()),
  ('추워', 'NEUTRAL', 1.0, NOW()),
  ('창문 열어줘', 'NEUTRAL', 1.0, NOW()),
  ('창문 닫아줘', 'NEUTRAL', 1.0, NOW()),
  ('에어컨 켜줘', 'NEUTRAL', 1.0, NOW()),
  ('에어컨 꺼줘', 'NEUTRAL', 1.0, NOW()),
  ('물리치료 받을래', 'NEUTRAL', 1.0, NOW()),
  ('물리치료 힘들었어', 'NEUTRAL', 1.0, NOW()),

  -- ===== 요청/일상 (40개) =====
  ('물 좀 줘', 'NEUTRAL', 1.0, NOW()),
  ('물 마시고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('목 말라', 'NEUTRAL', 1.0, NOW()),
  ('배고파', 'NEUTRAL', 1.0, NOW()),
  ('밥 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('국 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('죽 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('과일 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('도와줘', 'NEUTRAL', 1.0, NOW()),
  ('불 켜줘', 'NEUTRAL', 1.0, NOW()),
  ('불 꺼줘', 'NEUTRAL', 1.0, NOW()),
  ('TV 켜줘', 'NEUTRAL', 1.0, NOW()),
  ('TV 꺼줘', 'NEUTRAL', 1.0, NOW()),
  ('음악 틀어줘', 'NEUTRAL', 1.0, NOW()),
  ('트로트 틀어줘', 'NEUTRAL', 1.0, NOW()),
  ('라디오 틀어줘', 'NEUTRAL', 1.0, NOW()),
  ('소리 좀 줄여줘', 'NEUTRAL', 1.0, NOW()),
  ('소리 좀 키워줘', 'NEUTRAL', 1.0, NOW()),
  ('전화해줘', 'NEUTRAL', 1.0, NOW()),
  ('손 잡아줘', 'NEUTRAL', 1.0, NOW()),
  ('가까이 와줘', 'NEUTRAL', 1.0, NOW()),
  ('침대 올려줘', 'NEUTRAL', 1.0, NOW()),
  ('침대 내려줘', 'NEUTRAL', 1.0, NOW()),
  ('조금 더 줘', 'NEUTRAL', 1.0, NOW()),
  ('천천히 해줘', 'NEUTRAL', 1.0, NOW()),
  ('다시 해줘', 'NEUTRAL', 1.0, NOW()),
  ('살살 해줘', 'NEUTRAL', 1.0, NOW()),
  ('잠깐만', 'NEUTRAL', 1.0, NOW()),
  ('좀 있다가', 'NEUTRAL', 1.0, NOW()),
  ('지금 해줘', 'NEUTRAL', 1.0, NOW()),
  ('기다려줘', 'NEUTRAL', 1.0, NOW()),
  ('시간 몇 시야', 'NEUTRAL', 1.0, NOW()),
  ('오늘 무슨 요일이야', 'NEUTRAL', 1.0, NOW()),
  ('밖에 날씨 어때', 'NEUTRAL', 1.0, NOW()),
  ('비 와', 'NEUTRAL', 1.0, NOW()),
  ('날씨 좋아', 'NEUTRAL', 1.0, NOW()),
  ('좀 쉬어야겠어', 'NEUTRAL', 1.0, NOW()),
  ('그냥 좀 누워있을게', 'NEUTRAL', 1.0, NOW()),
  ('졸려', 'NEUTRAL', 1.0, NOW()),
  ('잠이 안 와', 'NEUTRAL', 1.0, NOW()),

  -- ===== 가족/손녀딸 (30개) =====
  ('손녀딸 보고 싶어', 'POSITIVE', 1.2, NOW()),
  ('손녀딸 언제 와', 'NEUTRAL', 1.2, NOW()),
  ('손녀딸 오늘 와', 'NEUTRAL', 1.2, NOW()),
  ('손녀딸 만나고 싶어', 'POSITIVE', 1.2, NOW()),
  ('손녀딸 기다려', 'POSITIVE', 1.2, NOW()),
  ('손녀딸 잘 있어', 'NEUTRAL', 1.2, NOW()),
  ('손녀딸 학교 갔어', 'NEUTRAL', 1.2, NOW()),
  ('손녀딸 생각나', 'POSITIVE', 1.2, NOW()),
  ('손녀딸한테 전화해줘', 'NEUTRAL', 1.2, NOW()),
  ('손녀딸 사진 보여줘', 'NEUTRAL', 1.2, NOW()),
  ('가족 보고 싶어', 'POSITIVE', 1.0, NOW()),
  ('딸 언제 와', 'NEUTRAL', 1.0, NOW()),
  ('아들 잘 있어', 'NEUTRAL', 1.0, NOW()),
  ('집사람 어디 갔어', 'NEUTRAL', 1.0, NOW()),
  ('손자 학교 잘 다녀', 'NEUTRAL', 1.0, NOW()),
  ('가족들 다 잘 지내', 'NEUTRAL', 1.0, NOW()),
  ('보고 싶다', 'POSITIVE', 1.0, NOW()),
  ('사랑해', 'POSITIVE', 1.0, NOW()),
  ('고맙다 진짜', 'POSITIVE', 1.0, NOW()),
  ('옆에 있어줘', 'NEUTRAL', 1.0, NOW()),
  ('혼자 있기 싫어', 'NEGATIVE', 1.0, NOW()),
  ('같이 있어줘', 'NEUTRAL', 1.0, NOW()),
  ('외출하고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('산책하고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('바깥 공기 쐬고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('누가 왔어', 'NEUTRAL', 1.0, NOW()),
  ('오늘 방문 있어', 'NEUTRAL', 1.0, NOW()),
  ('간호사 언제 와', 'NEUTRAL', 1.0, NOW()),
  ('선생님 언제 와', 'NEUTRAL', 1.0, NOW()),
  ('면회 가능해', 'NEUTRAL', 1.0, NOW()),

  -- ===== 야구/롯데 (20개) =====
  ('롯데 오늘 경기해', 'NEUTRAL', 1.2, NOW()),
  ('롯데 이겼어', 'POSITIVE', 1.2, NOW()),
  ('롯데 졌어', 'NEGATIVE', 1.2, NOW()),
  ('야구 보고 싶어', 'POSITIVE', 1.2, NOW()),
  ('야구 중계 틀어줘', 'NEUTRAL', 1.2, NOW()),
  ('롯데 몇 대 몇이야', 'NEUTRAL', 1.2, NOW()),
  ('오늘 선발 누구야', 'NEUTRAL', 1.2, NOW()),
  ('롯데 잘하고 있어', 'POSITIVE', 1.2, NOW()),
  ('야구 결과 알려줘', 'NEUTRAL', 1.2, NOW()),
  ('사직구장 가고 싶다', 'POSITIVE', 1.2, NOW()),
  ('야구 시즌이야', 'NEUTRAL', 1.0, NOW()),
  ('오늘 야구 있어', 'NEUTRAL', 1.0, NOW()),
  ('야구 점수 어떻게 돼', 'NEUTRAL', 1.0, NOW()),
  ('롯데 화이팅', 'POSITIVE', 1.2, NOW()),
  ('예전에 사직구장 자주 갔어', 'NEUTRAL', 1.0, NOW()),
  ('야구 보면 기분 좋아', 'POSITIVE', 1.0, NOW()),
  ('홈런 쳤어', 'POSITIVE', 1.0, NOW()),
  ('오늘 경기 몇 시야', 'NEUTRAL', 1.0, NOW()),
  ('내일 경기 있어', 'NEUTRAL', 1.0, NOW()),
  ('롯데 순위 어때', 'NEUTRAL', 1.0, NOW()),

  -- ===== 트로트/음악 (15개) =====
  ('트로트 듣고 싶어', 'POSITIVE', 1.2, NOW()),
  ('트로트 틀어줘', 'NEUTRAL', 1.2, NOW()),
  ('이 노래 좋다', 'POSITIVE', 1.0, NOW()),
  ('노래 한 번 더 틀어줘', 'NEUTRAL', 1.0, NOW()),
  ('이미자 노래 틀어줘', 'NEUTRAL', 1.0, NOW()),
  ('나훈아 노래 듣고 싶어', 'POSITIVE', 1.0, NOW()),
  ('음악 듣고 있으면 편해', 'POSITIVE', 1.0, NOW()),
  ('조용한 노래 틀어줘', 'NEUTRAL', 1.0, NOW()),
  ('노래 소리 좀 줄여줘', 'NEUTRAL', 1.0, NOW()),
  ('라디오에서 좋은 노래 나와', 'POSITIVE', 1.0, NOW()),
  ('옛날 노래 듣고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('음악 끄지 마', 'NEUTRAL', 1.0, NOW()),
  ('이 노래 제목이 뭐야', 'NEUTRAL', 1.0, NOW()),
  ('노래 들으니까 좋다', 'POSITIVE', 1.0, NOW()),
  ('트로트 들으면 기분 좋아', 'POSITIVE', 1.2, NOW()),

  -- ===== 식사/음식 (25개) =====
  ('밥 먹었어', 'NEUTRAL', 1.0, NOW()),
  ('아직 안 먹었어', 'NEUTRAL', 1.0, NOW()),
  ('맛있었어', 'POSITIVE', 1.0, NOW()),
  ('맛없었어', 'NEGATIVE', 1.0, NOW()),
  ('더 먹을게', 'NEUTRAL', 1.0, NOW()),
  ('배 불러', 'NEUTRAL', 1.0, NOW()),
  ('간식 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('따뜻한 거 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('시원한 거 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('김치찌개 먹고 싶어', 'POSITIVE', 1.0, NOW()),
  ('된장찌개 먹고 싶어', 'POSITIVE', 1.0, NOW()),
  ('국밥 먹고 싶어', 'POSITIVE', 1.0, NOW()),
  ('미역국 먹고 싶어', 'POSITIVE', 1.0, NOW()),
  ('수박 먹고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('우유 줘', 'NEUTRAL', 1.0, NOW()),
  ('커피 마시고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('차 한 잔 줘', 'NEUTRAL', 1.0, NOW()),
  ('물 한 모금만', 'NEUTRAL', 1.0, NOW()),
  ('좀 싱거워', 'NEUTRAL', 1.0, NOW()),
  ('좀 짜', 'NEUTRAL', 1.0, NOW()),
  ('뜨거워', 'NEUTRAL', 1.0, NOW()),
  ('차가워', 'NEUTRAL', 1.0, NOW()),
  ('조금만 줘', 'NEUTRAL', 1.0, NOW()),
  ('경관식 시간이야', 'NEUTRAL', 1.0, NOW()),
  ('물 좀 적셔줘', 'NEUTRAL', 1.0, NOW()),

  -- ===== 일상 대화 (30개) =====
  ('오늘 뭐 해', 'NEUTRAL', 1.0, NOW()),
  ('심심해', 'NEUTRAL', 1.0, NOW()),
  ('뭐 하고 있어', 'NEUTRAL', 1.0, NOW()),
  ('오늘 일정 알려줘', 'NEUTRAL', 1.0, NOW()),
  ('오늘 치료 있어', 'NEUTRAL', 1.0, NOW()),
  ('약 먹을 시간이야', 'NEUTRAL', 1.0, NOW()),
  ('밥 먹을 시간이야', 'NEUTRAL', 1.0, NOW()),
  ('아침 식사 할래', 'NEUTRAL', 1.0, NOW()),
  ('저녁 뭐 먹어', 'NEUTRAL', 1.0, NOW()),
  ('내일 뭐 해', 'NEUTRAL', 1.0, NOW()),
  ('그냥 그래', 'NEUTRAL', 1.0, NOW()),
  ('그저그래', 'NEUTRAL', 1.0, NOW()),
  ('뭐 별로 없어', 'NEUTRAL', 1.0, NOW()),
  ('그냥 있었어', 'NEUTRAL', 1.0, NOW()),
  ('특별한 거 없어', 'NEUTRAL', 1.0, NOW()),
  ('그냥 쉬고 있었어', 'NEUTRAL', 1.0, NOW()),
  ('TV 보고 있었어', 'NEUTRAL', 1.0, NOW()),
  ('낮잠 잤어', 'NEUTRAL', 1.0, NOW()),
  ('책 읽어줘', 'NEUTRAL', 1.0, NOW()),
  ('뉴스 보여줘', 'NEUTRAL', 1.0, NOW()),
  ('뭐 재밌는 거 없어', 'NEUTRAL', 1.0, NOW()),
  ('산책 가고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('햇빛 쬐고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('밖에 나가고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('집에 가고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('언제 퇴원해', 'NEUTRAL', 1.0, NOW()),
  ('오래 걸려', 'NEUTRAL', 1.0, NOW()),
  ('빨리 낫고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('나도 걷고 싶어', 'NEUTRAL', 1.0, NOW()),
  ('예전에는 좋았는데', 'NEUTRAL', 1.0, NOW());
