stages:
  - build-test

build_test_backend:
  stage: build-test
  image: amazoncorretto:21-alpine
  script:
    - cd backend
    - chmod +x gradlew
    - ./gradlew clean compileJava --no-daemon
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - backend/**/*

build_test_frontend:
  stage: build-test
  image: node:20-alpine
  script:
    - cd frontend
    - npm ci
    - npm run build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - frontend/**/*
