stages:
  - build-test

build_test:
  stage: build-test
  image: eclipse-temurin:21-jdk
  script:
    - cd backend
    - chmod +x gradlew
    - ./gradlew clean compileJava --no-daemon
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"