version: '3.8'
services:
  db-local:
    image: mysql:8.0
    container_name: eyespeak-db-local
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: eyespeak
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql-local-data:/var/lib/mysql

volumes:
  mysql-local-data: