export const API_ENDPOINTS = {
  AUTH_LOGIN: '/api/v1/auth/login',
  AUTH_LOGOUT: '/api/v1/auth/log-out',
  AUTH_SIGNUP_GUARDIAN: '/api/v1/auth/sign-up/guardian',
  AUTH_SIGNUP_PATIENT: '/api/v1/auth/patients',
  PATIENTS: '/api/v1/patients',
  ROUTINES: '/api/v1/routines',
  AUTH_RESET_PASSWORD: '/api/v1/auth/reset-password',
  AUTH_REFRESH: '/api/v1/auth/refresh',
  AUTH_WITHDRAW: '/api/v1/auth/withdraw',
  RECOMMENDATION_CATEGORIES: '/api/v1/recommendations/categories',
  RECOMMENDATION_SENTENCES: '/api/v1/recommendations/sentences',
  RECOMMENDATION_COMPOSE: '/api/v1/recommendations/compose',
  RECOMMENDATION_SEND: '/api/v1/recommendations/send',
  RECOMMENDATION_WORDS: '/api/v1/recommendations/words',
  RECOMMENDATION_REPLIES: '/api/v1/recommendations/replies',
  TTS_STATUS: '/api/v1/tts/status',
  TTS_VOICES: '/api/v1/tts/voices',
  TTS_TRAIN: '/api/v1/tts/train',
  TTS_SYNTHESIZE: '/api/v1/tts/synthesize',
  TTS_TEST: '/api/v1/tts/test',
  EYE_TRACKING_GAZE: '/api/gaze',
  EYE_TRACKING_CALIBRATE: '/api/calibrate',
  EYE_TRACKING_CALIBRATE_RESET: '/api/calibrate/reset',
  EYE_TRACKING_CALIBRATE_SAVE: '/api/calibrate/save',
  EYE_TRACKING_CALIBRATE_LOAD: '/api/calibrate/load',
  EYE_TRACKING_HEALTH: '/api/health',
} as const
